version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    steps:
      - checkout

      - run:
          name: Build
          command: dotnet build -c Release -p:Version=1.0.${CIRCLE_BUILD_NUM}

      - run:
          name: Unit tests
          command: dotnet test -c Release -p:Version=1.0.${CIRCLE_BUILD_NUM}
  deploy:
    # filters:
    #   branches:
    #     only:
    #       - master

    requires:
      - build

    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    steps:
      - run:
          name: Publish Nuget package
          command: dotnet nuget push Tftp.Net/bin/Release/Tftp.Net.1.0.${CIRCLE_BUILD_NUM}.nupkg --api-key ${NUGET_API_KEY}