version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    steps:
      - checkout

      - run:
          name: Build
          command: dotnet build -c Release -p:Version=1.0.${CIRCLE_BUILD_NUM}

      - run:
          name: Unit tests
          command: dotnet test -c Release --no-build -p:Version=1.0.${CIRCLE_BUILD_NUM}

      - persist_to_workspace:
          root: /bin
          paths:
            - Tftp.Net/bin/Release
  
  deploy:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    steps:
      - attach_workspace:
          at: /bin

      - run:
          name: test
          command: ls -lr

      - run:
          name: Publish Nuget package
          command: dotnet nuget push /bin/Tftp.Net.1.0.${CIRCLE_BUILD_NUM}.nupkg --api-key ${NUGET_API_KEY} --source https://api.nuget.org/v3/index.json

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build